name: Déploiement OVH

on:
  push:
    branches: [main]
    paths:
      - "wp-content/**"
  workflow_dispatch: {}

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Déploiement du thème vers OVH
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.OVH_FTP_SERVER }}
          username: ${{ secrets.OVH_FTP_USERNAME }}
          password: ${{ secrets.OVH_FTP_PASSWORD }}
          local-dir: ./wp-content/themes/atelier-benji/
          server-dir: ${{ secrets.OVH_FTP_THEME_DIR }}
          protocol: ftps
