name: Déploiement OVH

on:
  push:
    branches: [main]
    paths:
      - "wp-content/**"
  workflow_dispatch: {}

jobs:
  sftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Déploiement du thème vers OVH (SFTP)
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.OVH_FTP_SERVER }}
          port: 22
          username: ${{ secrets.OVH_FTP_USERNAME }}
          password: ${{ secrets.OVH_FTP_PASSWORD }}
          local_path: ./wp-content/themes/atelier-benji
          remote_path: ${{ secrets.OVH_FTP_THEME_DIR }}
          sftp_only: false
